"""Stable public API for the OPDS capability."""

from app.modules.opds.application.dto import (
    OPDS_ACQUISITION_REL,
    OPDS_PROGRESSION_MEDIA_TYPE,
    OPDS_PROGRESSION_REL,
    PSE_MEDIA_TYPES,
    PSE_STREAM_REL,
    BasicCredentialsDto,
    OpdsActorDto,
    OpdsAuthenticationRequestDto,
    OpdsAuthorDto,
    OpdsCatalogQueryDto,
    OpdsEntryDto,
    OpdsFeedDto,
    OpdsLinkDto,
    OpdsProgressionDeviceDto,
    OpdsProgressionDocumentDto,
    OpdsProgressionUpdateResultDto,
    PsePageRequestDto,
    PseStreamDto,
    normalize_pse_max_width,
    select_pse_stream_media_type,
)
from app.modules.opds.application.ports import (
    OpdsAuthenticator,
    OpdsCatalogPort,
    OpdsProgressionPort,
)
from app.modules.opds.application.settings import (
    OPDS_ENABLED_SETTING_KEY,
    OPDS_PUBLIC_BASE_URL_SETTING_KEY,
    OpdsPublicBaseUrlInvalid,
    OpdsPublicBaseUrlRequired,
    OpdsSettingsSnapshot,
    normalize_opds_public_base_url,
    resolve_opds_settings,
    validate_opds_activation,
)
from app.modules.opds.domain.errors import (
    OpdsAuthenticationRequired,
    OpdsProgressionDateConflict,
    OpdsProgressionIncorrectUser,
    OpdsProgressionInvalidPayload,
    OpdsProgressionLocked,
    OpdsPublicationNotFound,
)
from app.modules.opds.presentation.http import OpdsHttpDependencies, create_opds_router
from app.modules.opds.presentation.schemas import (
    OpdsAuthenticationDocument,
    OpdsAuthenticationFlow,
    OpdsAuthenticationLabels,
    OpdsProgressionDevice,
    OpdsProgressionDocument,
)

__all__ = [
    "OPDS_ACQUISITION_REL",
    "OPDS_ENABLED_SETTING_KEY",
    "OPDS_PROGRESSION_MEDIA_TYPE",
    "OPDS_PROGRESSION_REL",
    "OPDS_PUBLIC_BASE_URL_SETTING_KEY",
    "PSE_MEDIA_TYPES",
    "PSE_STREAM_REL",
    "BasicCredentialsDto",
    "OpdsActorDto",
    "OpdsAuthenticationDocument",
    "OpdsAuthenticationFlow",
    "OpdsAuthenticationLabels",
    "OpdsAuthenticationRequired",
    "OpdsAuthenticationRequestDto",
    "OpdsAuthenticator",
    "OpdsAuthorDto",
    "OpdsCatalogPort",
    "OpdsCatalogQueryDto",
    "OpdsEntryDto",
    "OpdsFeedDto",
    "OpdsHttpDependencies",
    "OpdsLinkDto",
    "OpdsProgressionDateConflict",
    "OpdsProgressionDevice",
    "OpdsProgressionDeviceDto",
    "OpdsProgressionDocument",
    "OpdsProgressionDocumentDto",
    "OpdsProgressionIncorrectUser",
    "OpdsProgressionInvalidPayload",
    "OpdsProgressionLocked",
    "OpdsProgressionPort",
    "OpdsProgressionUpdateResultDto",
    "OpdsPublicBaseUrlInvalid",
    "OpdsPublicBaseUrlRequired",
    "OpdsPublicationNotFound",
    "OpdsSettingsSnapshot",
    "PsePageRequestDto",
    "PseStreamDto",
    "create_opds_router",
    "normalize_opds_public_base_url",
    "normalize_pse_max_width",
    "resolve_opds_settings",
    "select_pse_stream_media_type",
    "validate_opds_activation",
]
