"""Explicit query contract used by media import decisions."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

Record = dict[str, object]


class ImportLibraryQueries(Protocol):
    def copy_shelf_links_to_work(
        self, source_work_ids: list[str], target_work_id: str
    ) -> None: ...

    def count_audio_chapters_for_media_version(self, media_version_id: str) -> int: ...
    def count_audio_chapters_for_volume(self, volume_id: str) -> int: ...
    def count_audio_files_for_media_version(self, media_version_id: str) -> int: ...
    def count_audiobook_media_kind_media_versions(
        self, work_id: str, media_kind: str
    ) -> int: ...
    def count_media_versions_for_work(
        self, work_id: str, *, media_kind: str | None = None
    ) -> int: ...
    def count_primary_audiobook_media_versions_for_work(
        self, work_id: str, *, exclude_media_version_id: str
    ) -> int: ...
    def count_visible_media_versions_for_work(self, work_id: str) -> int: ...
    def count_visible_volumes_for_work(self, work_id: str) -> int: ...
    def count_volumes_for_media_version(self, media_version_id: str) -> int: ...
    def delete_audio_metadata_sources(self, media_version_id: str) -> None: ...
    def detach_audio_chapters_for_media_version(
        self, media_version_id: str
    ) -> None: ...
    def detach_audio_chapters_for_media_version_or_files(
        self, media_version_id: str, file_ids: list[str]
    ) -> None: ...
    def existing_file_import_snapshot(self, path: Path) -> Record | None: ...
    def fail_import_assets_for_task(
        self,
        *,
        task_id: str,
        error_code: str,
        error_summary: str,
        updated_at: object,
    ) -> None: ...
    def find_audio_media_version_by_resource_key(
        self, resource_key: str
    ) -> Record | None: ...
    def find_deferred_source_volume(
        self, *, source_path: str, work_id: str, result_volume_id: str | None
    ) -> Record | None: ...
    def find_media_version_resource_key_conflict(
        self, work_id: str, resource_key: str, exclude_media_version_id: str
    ) -> Record | None: ...
    def find_work_cover_media_version(self, work_id: str) -> Record | None: ...
    def get_conversion_by_import_task_id(
        self, import_task_id: str
    ) -> Record | None: ...
    def get_media_version_by_id(self, media_version_id: str) -> Record | None: ...
    def get_media_version_cover_path(self, media_version_id: str) -> Record | None: ...
    def get_media_version_format(self, media_version_id: str) -> Record | None: ...
    def get_first_volume_for_media_version(
        self, media_version_id: str
    ) -> Record | None: ...
    def get_volume_context_by_id(self, volume_id: str) -> Record | None: ...
    def get_import_asset_by_task_and_path(
        self, task_id: str, source_path: str
    ) -> Record | None: ...
    def get_import_task_by_id(self, task_id: str) -> Record | None: ...
    def get_latest_audio_tags_metadata(
        self, media_version_id: str
    ) -> Record | None: ...
    def get_metadata_lookup_task_id_by_import(
        self, import_task_id: str
    ) -> Record | None: ...
    def get_organize_job_for_work_media_version(
        self, work_id: str, media_version_id: str
    ) -> Record | None: ...
    def get_pending_import_task_for_source(self, source_path: str) -> Record | None: ...
    def get_work_by_id(self, work_id: str) -> Record | None: ...
    def get_work_by_merge_key(self, merge_key: str) -> Record | None: ...
    def get_work_by_normalized_title(self, normalized_title: str) -> Record | None: ...
    def has_generated_cover_path(self, work_id: str, cover_path: str) -> bool: ...
    def list_audio_chapter_units_for_file_ordered(
        self, file_id: str
    ) -> list[Record]: ...
    def list_audio_chapters_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_audio_chapters_for_file(self, file_id: str) -> list[Record]: ...
    def list_audio_files_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_audio_files_for_volume(
        self, media_version_id: str, volume_id: str
    ) -> list[Record]: ...
    def list_audiobook_consumption_for_works(
        self, work_ids: list[str]
    ) -> list[Record]: ...
    def list_media_versions_by_ids(
        self, media_version_ids: list[str]
    ) -> list[Record]: ...
    def list_file_volumes_by_paths(self, paths: list[str]) -> list[Record]: ...
    def list_library_files_by_paths(self, paths: list[str]) -> list[Record]: ...
    def list_reflowable_chapters_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_reflowable_chapters_for_volume(self, volume_id: str) -> list[Record]: ...
    def list_reading_progress_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_reading_progress_for_media_versions(
        self, media_version_ids: list[str]
    ) -> list[Record]: ...
    def list_unassigned_audio_chapters_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_visible_media_versions_for_work_and_format(
        self, work_id: str, fmt: str
    ) -> list[Record]: ...
    def list_volume_cover_paths_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_volume_ordering_for_media_version(
        self, media_version_id: str
    ) -> list[Record]: ...
    def list_works_by_merge_key_prefix(self, merge_key_prefix: str) -> list[Record]: ...
    def sum_audio_duration_for_media_version(self, media_version_id: str) -> int: ...
    def sum_audio_duration_for_volume(self, volume_id: str) -> int: ...
    def sum_audio_file_size_for_media_version(self, media_version_id: str) -> int: ...
    def sum_file_size_bytes_for_media_version(self, media_version_id: str) -> int: ...
    def sum_volume_chapter_count_for_media_version(
        self, media_version_id: str
    ) -> int: ...
    def sum_volume_page_count_for_media_version(self, media_version_id: str) -> int: ...
