"""baseline_v14

Revision ID: 0001_current_schema
Revises:
Create Date: 2026-07-27 10:11:21.872441

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.core.time import TimestampMilliseconds

# revision identifiers, used by Alembic.
revision: str = "0001_current_schema"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "BookIdentityCache",
        sa.Column("logicalPath", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=False),
        sa.Column("volumeIndex", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("parserVersion", sa.Integer(), nullable=False),
        sa.Column("rawJson", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("logicalPath"),
    )
    with op.batch_alter_table("BookIdentityCache", schema=None) as batch_op:
        batch_op.create_index(
            "BookIdentityCache_parserVersion_idx", ["parserVersion"], unique=False
        )

    op.create_table(
        "DownloadTask",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("sourceId", sa.String(length=191), nullable=True),
        sa.Column("searchRecordId", sa.String(length=191), nullable=True),
        sa.Column("bookId", sa.String(length=191), nullable=True),
        sa.Column("type", sa.String(length=191), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("displayName", sa.Text(), nullable=False),
        sa.Column("remoteRef", sa.Text(), nullable=True),
        sa.Column("savePath", sa.Text(), nullable=True),
        sa.Column("filePath", sa.Text(), nullable=True),
        sa.Column("errorMessage", sa.Text(), nullable=True),
        sa.Column("progress", sa.Float(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("DownloadTask", schema=None) as batch_op:
        batch_op.create_index("DownloadTask_bookId_idx", ["bookId"], unique=False)
        batch_op.create_index(
            "DownloadTask_searchRecordId_idx", ["searchRecordId"], unique=False
        )
        batch_op.create_index("DownloadTask_sourceId_idx", ["sourceId"], unique=False)
        batch_op.create_index(
            "DownloadTask_status_createdAt_idx", ["status", "createdAt"], unique=False
        )
        batch_op.create_index("DownloadTask_type_idx", ["type"], unique=False)

    op.create_table(
        "ExternalMetadataCache",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("provider", sa.String(length=191), nullable=False),
        sa.Column("queryKey", sa.Text(), nullable=False),
        sa.Column("rawJson", sa.Text(), nullable=False),
        sa.Column("expiresAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ExternalMetadataCache", schema=None) as batch_op:
        batch_op.create_index(
            "ExternalMetadataCache_provider_expiresAt_idx",
            ["provider", "expiresAt"],
            unique=False,
        )
        batch_op.create_index(
            "ExternalMetadataCache_provider_queryKey_key",
            ["provider", "queryKey"],
            unique=True,
        )

    op.create_table(
        "LibraryFacet",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("normalizedName", sa.Text(), nullable=False),
        sa.Column("aliases", sa.Text(), server_default="[]", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("kind", "normalizedName"),
    )
    with op.batch_alter_table("LibraryFacet", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryFacet_kind_name_idx", ["kind", "name"], unique=False
        )

    op.create_table(
        "MetadataProviderPipeline",
        sa.Column("workType", sa.String(length=191), nullable=False),
        sa.Column("providerId", sa.String(length=191), nullable=False),
        sa.Column("included", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("position", sa.Integer(), server_default="100", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("workType", "providerId"),
    )
    with op.batch_alter_table("MetadataProviderPipeline", schema=None) as batch_op:
        batch_op.create_index(
            "MetadataProviderPipeline_workType_position_idx",
            ["workType", "included", "position"],
            unique=False,
        )

    op.create_table(
        "OrganizePolicy",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "scheduleMode",
            sa.String(length=191),
            server_default="MANUAL",
            nullable=False,
        ),
        sa.Column("intervalMinutes", sa.Integer(), server_default="60", nullable=False),
        sa.Column("autoRunOnNew", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("autoRunOnNewSince", TimestampMilliseconds(), nullable=True),
        sa.Column("rulesJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column(
            "overwriteTitleAuthor", sa.Boolean(), server_default="1", nullable=False
        ),
        sa.Column("lastScheduledAt", TimestampMilliseconds(), nullable=True),
        sa.Column("nextRunAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "OrganizeRun",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("trigger", sa.String(length=191), nullable=False),
        sa.Column("scopeJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column("dedupeKey", sa.String(length=191), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="QUEUED", nullable=False
        ),
        sa.Column("queuedCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("completedCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reviewCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("failedCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dedupeKey"),
    )
    with op.batch_alter_table("OrganizeRun", schema=None) as batch_op:
        batch_op.create_index(
            "OrganizeRun_status_createdAt_idx", ["status", "createdAt"], unique=False
        )

    op.create_table(
        "QueueControlOperation",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("queueName", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("actorUserId", sa.String(length=191), nullable=False),
        sa.Column("messageCode", sa.String(length=191), nullable=True),
        sa.Column("requestedAt", TimestampMilliseconds(), nullable=False),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("QueueControlOperation", schema=None) as batch_op:
        batch_op.create_index(
            "QueueControlOperation_queue_status_idx",
            ["queueName", "status", "requestedAt"],
            unique=False,
        )

    op.create_table(
        "QueueRuntimeState",
        sa.Column("queueName", sa.String(length=64), nullable=False),
        sa.Column("instanceId", sa.String(length=191), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("pollIntervalSeconds", sa.Float(), nullable=False),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=False),
        sa.Column("heartbeatAt", TimestampMilliseconds(), nullable=False),
        sa.Column("lastProcessedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("lastError", sa.Text(), nullable=True),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("queueName"),
    )
    op.create_table(
        "Source",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("providerType", sa.String(length=191), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("config", sa.Text(), nullable=True),
        sa.Column("credentialsKey", sa.String(length=191), nullable=True),
        sa.Column("capabilities", sa.Text(), nullable=True),
        sa.Column("rateLimit", sa.Text(), nullable=True),
        sa.Column("lastTestAt", TimestampMilliseconds(), nullable=True),
        sa.Column("lastTestStatus", sa.String(length=191), nullable=True),
        sa.Column("lastError", sa.Text(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("Source", schema=None) as batch_op:
        batch_op.create_index("Source_enabled_idx", ["enabled"], unique=False)
        batch_op.create_index("Source_kind_idx", ["kind"], unique=False)
        batch_op.create_index("Source_priority_idx", ["priority"], unique=False)
        batch_op.create_index("Source_providerType_idx", ["providerType"], unique=False)

    op.create_table(
        "SystemEvent",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column(
            "level", sa.String(length=191), server_default="info", nullable=False
        ),
        sa.Column("source", sa.String(length=191), nullable=False),
        sa.Column(
            "actorType", sa.String(length=191), server_default="system", nullable=False
        ),
        sa.Column("actorId", sa.String(length=191), nullable=True),
        sa.Column("action", sa.String(length=191), nullable=False),
        sa.Column("targetType", sa.String(length=191), nullable=True),
        sa.Column("targetId", sa.String(length=191), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("SystemEvent", schema=None) as batch_op:
        batch_op.create_index(
            "SystemEvent_action_createdAt_idx", ["action", "createdAt"], unique=False
        )
        batch_op.create_index(
            "SystemEvent_actorType_createdAt_idx",
            ["actorType", "createdAt"],
            unique=False,
        )
        batch_op.create_index("SystemEvent_createdAt_idx", ["createdAt"], unique=False)
        batch_op.create_index(
            "SystemEvent_level_createdAt_idx", ["level", "createdAt"], unique=False
        )
        batch_op.create_index(
            "SystemEvent_source_createdAt_idx", ["source", "createdAt"], unique=False
        )
        batch_op.create_index(
            "SystemEvent_targetType_targetId_idx",
            ["targetType", "targetId"],
            unique=False,
        )

    op.create_table(
        "SystemHealthRun",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("actorUserId", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="running", nullable=False
        ),
        sa.Column("version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("snapshot", sa.Text(), nullable=False),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=False),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "SystemSetting",
        sa.Column("key", sa.String(length=191), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "User",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("email", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("passwordHash", sa.String(length=191), nullable=False),
        sa.Column("avatarPath", sa.String(length=500), nullable=True),
        sa.Column(
            "role", sa.String(length=191), server_default="member", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=32), server_default="active", nullable=False
        ),
        sa.Column("canManageSystem", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "canViewManualImports", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("authzVersion", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "LibraryOperation",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=True),
        sa.Column("action", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default="COMPLETED", nullable=False
        ),
        sa.Column("targetType", sa.String(length=191), nullable=True),
        sa.Column("targetId", sa.String(length=191), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("payloadJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column("inverseJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column("expiresAt", TimestampMilliseconds(), nullable=True),
        sa.Column("undoneAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryOperation", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryOperation_action_createdAt_idx",
            ["action", "createdAt"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryOperation_status_expiresAt_idx",
            ["status", "expiresAt"],
            unique=False,
        )

    op.create_table(
        "PasswordResetToken",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("tokenHash", sa.String(length=64), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("expiresAt", TimestampMilliseconds(), nullable=False),
        sa.Column("usedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tokenHash"),
    )
    with op.batch_alter_table("PasswordResetToken", schema=None) as batch_op:
        batch_op.create_index(
            "PasswordResetToken_expiresAt_idx", ["expiresAt"], unique=False
        )
        batch_op.create_index(
            "PasswordResetToken_userId_createdAt_idx",
            ["userId", "createdAt"],
            unique=False,
        )

    op.create_table(
        "ReaderPreference",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("readerType", sa.String(length=191), nullable=False),
        sa.Column("settings", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "userId", "readerType", name="ReaderPreference_userId_readerType_key"
        ),
    )
    with op.batch_alter_table("ReaderPreference", schema=None) as batch_op:
        batch_op.create_index("ReaderPreference_userId_idx", ["userId"], unique=False)

    op.create_table(
        "Session",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("tokenHash", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("expiresAt", TimestampMilliseconds(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tokenHash"),
    )
    op.create_table(
        "Shelf",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("ownerUserId", sa.String(length=191), nullable=True),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "kind", sa.String(length=191), server_default="STATIC", nullable=False
        ),
        sa.Column("rulesJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column("pinned", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ownerUserId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("Shelf", schema=None) as batch_op:
        batch_op.create_index(
            "Shelf_kind_updatedAt_idx", ["kind", "updatedAt"], unique=False
        )
        batch_op.create_index(
            "Shelf_ownerUserId_updatedAt_idx",
            ["ownerUserId", "updatedAt"],
            unique=False,
        )
        batch_op.create_index("Shelf_updatedAt_idx", ["updatedAt"], unique=False)

    op.create_table(
        "SourceSearchRecord",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("sourceId", sa.String(length=191), nullable=False),
        sa.Column("providerType", sa.String(length=191), nullable=False),
        sa.Column("externalId", sa.String(length=191), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("subtitle", sa.Text(), nullable=True),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("coverUrl", sa.Text(), nullable=True),
        sa.Column("externalUrl", sa.Text(), nullable=True),
        sa.Column("format", sa.String(length=191), nullable=True),
        sa.Column("size", sa.String(length=191), nullable=True),
        sa.Column("language", sa.String(length=191), nullable=True),
        sa.Column("publishedAt", sa.String(length=191), nullable=True),
        sa.Column(
            "downloadAvailable", sa.Boolean(), server_default="0", nullable=False
        ),
        sa.Column("downloadMeta", sa.Text(), nullable=True),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), server_default="new", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sourceId"], ["Source.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "sourceId", "externalId", name="SourceSearchRecord_sourceId_externalId_key"
        ),
    )
    with op.batch_alter_table("SourceSearchRecord", schema=None) as batch_op:
        batch_op.create_index(
            "SourceSearchRecord_createdAt_idx", ["createdAt"], unique=False
        )
        batch_op.create_index(
            "SourceSearchRecord_providerType_idx", ["providerType"], unique=False
        )
        batch_op.create_index(
            "SourceSearchRecord_sourceId_idx", ["sourceId"], unique=False
        )
        batch_op.create_index("SourceSearchRecord_status_idx", ["status"], unique=False)
        batch_op.create_index("SourceSearchRecord_title_idx", ["title"], unique=False)

    op.create_table(
        "UserPreference",
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("key", sa.String(length=191), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("userId", "key"),
    )
    with op.batch_alter_table("UserPreference", schema=None) as batch_op:
        batch_op.create_index("UserPreference_userId_idx", ["userId"], unique=False)

    op.create_table(
        "MonitorFolder",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("rootPath", sa.String(length=191), nullable=False),
        sa.Column("shelfId", sa.String(length=191), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="1", nullable=False),
        sa.Column("ignorePatterns", sa.Text(), nullable=True),
        sa.Column("ignoreHidden", sa.Boolean(), server_default="1", nullable=False),
        sa.Column(
            "minFileSizeBytes", sa.Integer(), server_default="10240", nullable=False
        ),
        sa.Column("description", sa.String(length=191), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shelfId"], ["Shelf.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rootPath"),
    )
    op.create_table(
        "LibraryWork",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("monitorFolderId", sa.String(length=191), nullable=True),
        sa.Column(
            "origin", sa.String(length=191), server_default="MANUAL", nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("normalizedTitle", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("normalizedAuthor", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("workType", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default="UNREAD", nullable=False
        ),
        sa.Column(
            "publicationStatus",
            sa.String(length=191),
            server_default="UNKNOWN",
            nullable=False,
        ),
        sa.Column(
            "trackingStatus",
            sa.String(length=191),
            server_default="NOT_TRACKING",
            nullable=False,
        ),
        sa.Column("localLatestVolume", sa.Float(), nullable=True),
        sa.Column("localLatestChapter", sa.Float(), nullable=True),
        sa.Column("localLatestTitle", sa.Text(), nullable=True),
        sa.Column("localLatestAt", TimestampMilliseconds(), nullable=True),
        sa.Column("tags", sa.Text(), nullable=False),
        sa.Column("seriesName", sa.Text(), nullable=True),
        sa.Column("seriesIndex", sa.Float(), nullable=True),
        sa.Column("publishedYear", sa.Integer(), nullable=True),
        sa.Column("metadataQuality", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "organizeStatus",
            sa.String(length=191),
            server_default="REVIEWING",
            nullable=False,
        ),
        sa.Column("coverPath", sa.Text(), nullable=True),
        sa.Column(
            "coverStatus",
            sa.String(length=191),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("organized", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("primaryEditionId", sa.String(length=191), nullable=True),
        sa.Column("mergeKey", sa.Text(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitorFolderId"],
            ["MonitorFolder.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryWork", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryWork_createdAt_id_idx", ["createdAt", "id"], unique=False
        )
        batch_op.create_index("LibraryWork_hidden_idx", ["hidden"], unique=False)
        batch_op.create_index("LibraryWork_mergeKey_idx", ["mergeKey"], unique=False)
        batch_op.create_index(
            "LibraryWork_monitorFolderId_idx", ["monitorFolderId"], unique=False
        )
        batch_op.create_index(
            "LibraryWork_normalizedAuthor_idx", ["normalizedAuthor"], unique=False
        )
        batch_op.create_index(
            "LibraryWork_normalizedTitle_idx", ["normalizedTitle"], unique=False
        )
        batch_op.create_index(
            "LibraryWork_organizeStatus_idx", ["organizeStatus"], unique=False
        )
        batch_op.create_index("LibraryWork_organized_idx", ["organized"], unique=False)
        batch_op.create_index(
            "LibraryWork_publicationStatus_idx", ["publicationStatus"], unique=False
        )
        batch_op.create_index(
            "LibraryWork_publishedYear_idx", ["publishedYear"], unique=False
        )
        batch_op.create_index(
            "LibraryWork_seriesName_idx", ["seriesName"], unique=False
        )
        batch_op.create_index("LibraryWork_title_idx", ["title"], unique=False)
        batch_op.create_index(
            "LibraryWork_trackingStatus_idx", ["trackingStatus"], unique=False
        )
        batch_op.create_index("LibraryWork_workType_idx", ["workType"], unique=False)

    op.create_table(
        "UserMonitorFolderAccess",
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("monitorFolderId", sa.String(length=191), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["monitorFolderId"],
            ["MonitorFolder.id"],
            ondelete="CASCADE",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("userId", "monitorFolderId"),
    )
    with op.batch_alter_table("UserMonitorFolderAccess", schema=None) as batch_op:
        batch_op.create_index(
            "UserMonitorFolderAccess_folder_idx", ["monitorFolderId"], unique=False
        )

    op.create_table(
        "LibraryEdition",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("monitorFolderId", sa.String(length=191), nullable=True),
        sa.Column(
            "origin", sa.String(length=191), server_default="MANUAL", nullable=False
        ),
        sa.Column(
            "mediaKind", sa.String(length=191), server_default="EBOOK", nullable=False
        ),
        sa.Column("format", sa.String(length=191), nullable=False),
        sa.Column("versionName", sa.Text(), nullable=False),
        sa.Column("versionKey", sa.String(length=191), nullable=False),
        sa.Column("sourceGroupKey", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=191), nullable=True),
        sa.Column("publisher", sa.Text(), nullable=True),
        sa.Column("publishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("identifier", sa.Text(), nullable=True),
        sa.Column("isbn", sa.String(length=191), nullable=True),
        sa.Column(
            "importStatus",
            sa.String(length=191),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("importError", sa.Text(), nullable=True),
        sa.Column("sizeBytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pageCount", sa.Integer(), nullable=True),
        sa.Column("chapterCount", sa.Integer(), nullable=True),
        sa.Column("durationMs", sa.Integer(), nullable=True),
        sa.Column("trackCount", sa.Integer(), nullable=True),
        sa.Column("narrator", sa.Text(), nullable=True),
        sa.Column("abridged", sa.Boolean(), nullable=True),
        sa.Column("coverPath", sa.Text(), nullable=True),
        sa.Column(
            "coverStatus",
            sa.String(length=191),
            server_default="PENDING",
            nullable=False,
        ),
        sa.Column("primary", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("hidden", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["monitorFolderId"],
            ["MonitorFolder.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryEdition", schema=None) as batch_op:
        batch_op.create_index("LibraryEdition_format_idx", ["format"], unique=False)
        batch_op.create_index(
            "LibraryEdition_identifier_idx", ["identifier"], unique=False
        )
        batch_op.create_index("LibraryEdition_isbn_idx", ["isbn"], unique=False)
        batch_op.create_index(
            "LibraryEdition_monitorFolderId_idx", ["monitorFolderId"], unique=False
        )
        batch_op.create_index(
            "LibraryEdition_sourceGroupKey_idx", ["sourceGroupKey"], unique=False
        )
        batch_op.create_index(
            "LibraryEdition_workId_mediaKind_idx", ["workId", "mediaKind"], unique=False
        )
        batch_op.create_index(
            "LibraryEdition_workId_mediaKind_primary_key",
            ["workId", "mediaKind"],
            unique=True,
            sqlite_where=sa.text("`primary` = 1 AND `hidden` = 0"),
        )
        batch_op.create_index(
            "LibraryEdition_workId_primary_idx", ["workId", "primary"], unique=False
        )
        batch_op.create_index(
            "LibraryEdition_workId_versionKey_key",
            ["workId", "versionKey"],
            unique=True,
        )

    op.create_table(
        "LibraryWorkFacet",
        sa.Column("facetId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["facetId"], ["LibraryFacet.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("facetId", "workId"),
    )
    with op.batch_alter_table("LibraryWorkFacet", schema=None) as batch_op:
        batch_op.create_index("LibraryWorkFacet_workId_idx", ["workId"], unique=False)

    op.create_table(
        "ReaderBookPreference",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("schemaVersion", sa.Integer(), server_default="3", nullable=False),
        sa.Column("preferences", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "userId", "workId", name="ReaderBookPreference_userId_workId_key"
        ),
    )
    with op.batch_alter_table("ReaderBookPreference", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ReaderBookPreference_userId"), ["userId"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ReaderBookPreference_workId"), ["workId"], unique=False
        )

    op.create_table(
        "ReaderProgressCursor",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("clientId", sa.String(length=191), nullable=False),
        sa.Column("highWater", sa.BigInteger(), server_default="-1", nullable=False),
        sa.Column("lastMutationId", sa.String(length=191), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "userId",
            "workId",
            "clientId",
            name="ReaderProgressCursor_userId_workId_clientId_key",
        ),
    )
    with op.batch_alter_table("ReaderProgressCursor", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ReaderProgressCursor_userId"), ["userId"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ReaderProgressCursor_workId"), ["workId"], unique=False
        )

    op.create_table(
        "ShelfWork",
        sa.Column("shelfId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["shelfId"], ["Shelf.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("shelfId", "workId"),
    )
    with op.batch_alter_table("ShelfWork", schema=None) as batch_op:
        batch_op.create_index(
            "ShelfWork_shelfId_createdAt_idx", ["shelfId", "createdAt"], unique=False
        )
        batch_op.create_index("ShelfWork_workId_idx", ["workId"], unique=False)

    op.create_table(
        "WorkDetailPreference",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("selectedTab", sa.String(length=191), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("WorkDetailPreference", schema=None) as batch_op:
        batch_op.create_index(
            "WorkDetailPreference_user_work_key", ["userId", "workId"], unique=True
        )

    op.create_table(
        "LibraryEditionFacet",
        sa.Column("facetId", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["facetId"], ["LibraryFacet.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("facetId", "editionId"),
    )
    with op.batch_alter_table("LibraryEditionFacet", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryEditionFacet_editionId_idx", ["editionId"], unique=False
        )

    op.create_table(
        "LibraryMetadata",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("source", sa.String(length=191), nullable=False),
        sa.Column("rawJson", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryMetadata", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryMetadata_editionId_idx", ["editionId"], unique=False
        )

    op.create_table(
        "LibraryVolume",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("volumeIndex", sa.Float(), nullable=True),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pageCount", sa.Integer(), nullable=True),
        sa.Column("chapterCount", sa.Integer(), nullable=True),
        sa.Column("durationMs", sa.Integer(), nullable=True),
        sa.Column("coverPath", sa.Text(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryVolume", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryVolume_editionId_sortOrder_idx",
            ["editionId", "sortOrder"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryVolume_editionId_volumeIndex_idx",
            ["editionId", "volumeIndex"],
            unique=False,
        )

    op.create_table(
        "ReaderBookmark",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("contentFingerprint", sa.String(length=191), nullable=False),
        sa.Column("bookmarkId", sa.Text(), nullable=False),
        sa.Column("locationJson", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("percent", sa.Float(), server_default="0", nullable=False),
        sa.Column("bookmarkCreatedAt", sa.String(length=64), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "userId",
            "editionId",
            "contentFingerprint",
            "bookmarkId",
            name="ReaderBookmark_user_edition_fingerprint_bookmark_key",
        ),
    )
    with op.batch_alter_table("ReaderBookmark", schema=None) as batch_op:
        batch_op.create_index(
            "ReaderBookmark_user_edition_idx", ["userId", "editionId"], unique=False
        )

    op.create_table(
        "ImportTask",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("monitorFolderId", sa.String(length=191), nullable=True),
        sa.Column("workId", sa.String(length=191), nullable=True),
        sa.Column("editionId", sa.String(length=191), nullable=True),
        sa.Column("volumeId", sa.String(length=191), nullable=True),
        sa.Column("origin", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("originalName", sa.Text(), nullable=True),
        sa.Column("requestedTitle", sa.Text(), nullable=True),
        sa.Column("requestedAuthor", sa.Text(), nullable=True),
        sa.Column("sourcePath", sa.Text(), nullable=False),
        sa.Column("contentHash", sa.String(length=191), nullable=True),
        sa.Column(
            "taskKind", sa.String(length=191), server_default="FILE", nullable=False
        ),
        sa.Column("bundleKey", sa.String(length=191), nullable=True),
        sa.Column("assetCount", sa.Integer(), server_default="1", nullable=False),
        sa.Column(
            "processedAssetCount", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duplicate", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("duration", sa.Integer(), server_default="0", nullable=False),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column("errorCode", sa.String(length=191), nullable=True),
        sa.Column("retryable", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("leaseOwner", sa.String(length=191), nullable=True),
        sa.Column("leaseExpiresAt", TimestampMilliseconds(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"],
            ["LibraryEdition.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["monitorFolderId"],
            ["MonitorFolder.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["volumeId"], ["LibraryVolume.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ImportTask", schema=None) as batch_op:
        batch_op.create_index(
            "ImportTask_contentHash_idx", ["contentHash"], unique=False
        )
        batch_op.create_index(
            "ImportTask_createdAt_id_idx", ["createdAt", "id"], unique=False
        )
        batch_op.create_index("ImportTask_editionId_idx", ["editionId"], unique=False)
        batch_op.create_index(
            "ImportTask_monitorFolderId_status_idx",
            ["monitorFolderId", "status"],
            unique=False,
        )
        batch_op.create_index(
            "ImportTask_status_createdAt_idx", ["status", "createdAt"], unique=False
        )
        batch_op.create_index(
            "ImportTask_status_leaseExpiresAt_idx",
            ["status", "leaseExpiresAt"],
            unique=False,
        )
        batch_op.create_index("ImportTask_volumeId_idx", ["volumeId"], unique=False)
        batch_op.create_index("ImportTask_workId_idx", ["workId"], unique=False)

    op.create_table(
        "LibraryFile",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("volumeId", sa.String(length=191), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("filePathHash", sa.String(length=191), nullable=True),
        sa.Column("fingerprint", sa.Text(), nullable=True),
        sa.Column("fullHash", sa.String(length=191), nullable=True),
        sa.Column(
            "hashStatus", sa.String(length=191), server_default="FAILED", nullable=False
        ),
        sa.Column("mtimeMs", sa.Integer(), server_default="0", nullable=False),
        sa.Column("kind", sa.String(length=191), nullable=False),
        sa.Column("mimeType", sa.String(length=191), nullable=False),
        sa.Column("sizeBytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("durationMs", sa.Integer(), nullable=True),
        sa.Column("codec", sa.String(length=191), nullable=True),
        sa.Column("bitrate", sa.Integer(), nullable=True),
        sa.Column("sampleRate", sa.Integer(), nullable=True),
        sa.Column("channels", sa.Integer(), nullable=True),
        sa.Column("discNumber", sa.Integer(), nullable=True),
        sa.Column("trackNumber", sa.Integer(), nullable=True),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volumeId"], ["LibraryVolume.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryFile", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryFile_editionId_sortOrder_idx",
            ["editionId", "sortOrder"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryFile_filePathHash_key", ["filePathHash"], unique=True
        )
        batch_op.create_index(
            "LibraryFile_fingerprint_idx", ["fingerprint"], unique=False
        )
        batch_op.create_index("LibraryFile_fullHash_idx", ["fullHash"], unique=False)
        batch_op.create_index("LibraryFile_fullHash_key", ["fullHash"], unique=True)
        batch_op.create_index("LibraryFile_path_key", ["path"], unique=True)
        batch_op.create_index(
            "LibraryFile_sizeBytes_mtimeMs_idx", ["sizeBytes", "mtimeMs"], unique=False
        )
        batch_op.create_index(
            "LibraryFile_volumeId_sortOrder_idx",
            ["volumeId", "sortOrder"],
            unique=False,
        )

    op.create_table(
        "LibraryReadingProgress",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("volumeId", sa.String(length=191), nullable=True),
        sa.Column("readerType", sa.String(length=191), nullable=False),
        sa.Column("position", sa.Text(), server_default="0", nullable=False),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("percent", sa.Float(), server_default="0", nullable=False),
        sa.Column("extra", sa.Text(), nullable=False),
        sa.Column("schemaVersion", sa.Integer(), server_default="1", nullable=False),
        sa.Column("locationType", sa.String(length=191), nullable=True),
        sa.Column("locationJson", sa.Text(), nullable=True),
        sa.Column("contentFingerprint", sa.String(length=191), nullable=True),
        sa.Column("mutationId", sa.String(length=191), nullable=True),
        sa.Column("clientId", sa.String(length=191), nullable=True),
        sa.Column("clientSequence", sa.Integer(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volumeId"], ["LibraryVolume.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryReadingProgress", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryReadingProgress_clientId_clientSequence_idx",
            ["clientId", "clientSequence"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryReadingProgress_editionId_idx", ["editionId"], unique=False
        )
        batch_op.create_index(
            "LibraryReadingProgress_userId_editionId_volumeId_key",
            ["userId", "editionId", "volumeId"],
            unique=True,
        )
        batch_op.create_index(
            "LibraryReadingProgress_volumeId_idx", ["volumeId"], unique=False
        )
        batch_op.create_index(
            "LibraryReadingProgress_workId_idx", ["workId"], unique=False
        )

    op.create_table(
        "BookConversionTask",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("importTaskId", sa.String(length=191), nullable=False),
        sa.Column("mode", sa.String(length=191), server_default="AUTO", nullable=False),
        sa.Column("sourceFormat", sa.String(length=191), nullable=False),
        sa.Column(
            "targetFormat", sa.String(length=191), server_default="EPUB", nullable=False
        ),
        sa.Column("sourcePath", sa.Text(), nullable=False),
        sa.Column("outputPath", sa.Text(), nullable=True),
        sa.Column("sourceHash", sa.String(length=191), nullable=True),
        sa.Column(
            "converter",
            sa.String(length=191),
            server_default="booknook-internal",
            nullable=False,
        ),
        sa.Column("converterVersion", sa.String(length=191), nullable=True),
        sa.Column("optionsJson", sa.Text(), server_default="{}", nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="QUEUED", nullable=False
        ),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("retryable", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("errorCode", sa.String(length=191), nullable=True),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["importTaskId"], ["ImportTask.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("importTaskId"),
    )
    with op.batch_alter_table("BookConversionTask", schema=None) as batch_op:
        batch_op.create_index(
            "BookConversionTask_sourceHash_idx", ["sourceHash"], unique=False
        )
        batch_op.create_index(
            "BookConversionTask_status_createdAt_idx",
            ["status", "createdAt"],
            unique=False,
        )

    op.create_table(
        "ImportAsset",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("importTaskId", sa.String(length=191), nullable=False),
        sa.Column("sourcePath", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("sortOrder", sa.Integer(), server_default="0", nullable=False),
        sa.Column("fileId", sa.String(length=191), nullable=True),
        sa.Column("errorCode", sa.String(length=191), nullable=True),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fileId"], ["LibraryFile.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["importTaskId"], ["ImportTask.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "importTaskId", "sourcePath", name="ImportAsset_importTaskId_sourcePath_key"
        ),
    )
    with op.batch_alter_table("ImportAsset", schema=None) as batch_op:
        batch_op.create_index(
            "ImportAsset_importTaskId_sortOrder_idx",
            ["importTaskId", "sortOrder"],
            unique=False,
        )

    op.create_table(
        "ImportLog",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("importTaskId", sa.String(length=191), nullable=False),
        sa.Column(
            "level", sa.String(length=191), server_default="info", nullable=False
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["importTaskId"], ["ImportTask.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ImportLog", schema=None) as batch_op:
        batch_op.create_index(
            "ImportLog_importTaskId_createdAt_idx",
            ["importTaskId", "createdAt"],
            unique=False,
        )

    op.create_table(
        "KindleSendTask",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=True),
        sa.Column("workId", sa.String(length=191), nullable=True),
        sa.Column("editionId", sa.String(length=191), nullable=True),
        sa.Column("volumeId", sa.String(length=191), nullable=True),
        sa.Column("fileId", sa.String(length=191), nullable=True),
        sa.Column("bookTitle", sa.Text(), nullable=False),
        sa.Column("editionName", sa.Text(), nullable=True),
        sa.Column("volumeTitle", sa.Text(), nullable=True),
        sa.Column("fileName", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=191), nullable=False),
        sa.Column("mimeType", sa.String(length=191), nullable=False),
        sa.Column("sizeBytes", sa.Integer(), server_default="0", nullable=False),
        sa.Column("senderEmail", sa.String(length=191), nullable=True),
        sa.Column("recipientEmail", sa.String(length=191), nullable=False),
        sa.Column("subject", sa.Text(), nullable=False),
        sa.Column("smtpHost", sa.String(length=191), nullable=True),
        sa.Column("smtpPort", sa.Integer(), nullable=True),
        sa.Column("smtpSecurity", sa.String(length=191), nullable=True),
        sa.Column("smtpUsername", sa.String(length=191), nullable=True),
        sa.Column("messageId", sa.String(length=191), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="queued", nullable=False
        ),
        sa.Column("attemptCount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nextAttemptAt", TimestampMilliseconds(), nullable=True),
        sa.Column("errorMessage", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("sentAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"],
            ["LibraryEdition.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fileId"], ["LibraryFile.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volumeId"], ["LibraryVolume.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("KindleSendTask", schema=None) as batch_op:
        batch_op.create_index(
            "KindleSendTask_active_file_recipient_key",
            ["fileId", "recipientEmail"],
            unique=True,
            sqlite_where=sa.text("status IN ('queued', 'sending')"),
        )
        batch_op.create_index(
            "KindleSendTask_status_nextAttemptAt_createdAt_idx",
            ["status", "nextAttemptAt", "createdAt"],
            unique=False,
        )
        batch_op.create_index(
            "KindleSendTask_userId_createdAt_idx", ["userId", "createdAt"], unique=False
        )
        batch_op.create_index(
            "KindleSendTask_workId_createdAt_idx", ["workId", "createdAt"], unique=False
        )

    op.create_table(
        "LibraryReadingUnit",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=False),
        sa.Column("volumeId", sa.String(length=191), nullable=True),
        sa.Column("fileId", sa.String(length=191), nullable=True),
        sa.Column("unitType", sa.String(length=191), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("href", sa.Text(), nullable=False),
        sa.Column("mediaType", sa.String(length=191), nullable=True),
        sa.Column("sortOrder", sa.Integer(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("startMs", sa.Integer(), nullable=True),
        sa.Column("endMs", sa.Integer(), nullable=True),
        sa.Column("durationMs", sa.Integer(), nullable=True),
        sa.Column("metadataJson", sa.Text(), nullable=False),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"], ["LibraryEdition.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["fileId"], ["LibraryFile.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["volumeId"], ["LibraryVolume.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryReadingUnit", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryReadingUnit_editionId_sortOrder_idx",
            ["editionId", "sortOrder"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryReadingUnit_editionId_unitType_idx",
            ["editionId", "unitType"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryReadingUnit_fileId_sortOrder_idx",
            ["fileId", "sortOrder"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryReadingUnit_volumeId_sortOrder_idx",
            ["volumeId", "sortOrder"],
            unique=False,
        )
        batch_op.create_index(
            "LibraryReadingUnit_volumeId_unitType_sortOrder_key",
            ["volumeId", "unitType", "sortOrder"],
            unique=True,
        )

    op.create_table(
        "OrganizeJob",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("runId", sa.String(length=191), nullable=True),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=True),
        sa.Column("importTaskId", sa.String(length=191), nullable=True),
        sa.Column(
            "trigger", sa.String(length=191), server_default="LEGACY", nullable=False
        ),
        sa.Column(
            "status", sa.String(length=32), server_default="REVIEWING", nullable=False
        ),
        sa.Column("issueCodes", sa.Text(), nullable=False),
        sa.Column("reasonCodes", sa.Text(), server_default="[]", nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"],
            ["LibraryEdition.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["importTaskId"], ["ImportTask.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["runId"], ["OrganizeRun.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("OrganizeJob", schema=None) as batch_op:
        batch_op.create_index("OrganizeJob_editionId_idx", ["editionId"], unique=False)
        batch_op.create_index(
            "OrganizeJob_importTaskId_idx", ["importTaskId"], unique=False
        )
        batch_op.create_index(
            "OrganizeJob_runId_status_idx", ["runId", "status"], unique=False
        )
        batch_op.create_index(
            "OrganizeJob_status_updatedAt_idx", ["status", "updatedAt"], unique=False
        )
        batch_op.create_index(
            "OrganizeJob_unresolved_workId_key",
            ["workId"],
            unique=True,
            sqlite_where=sa.text(
                "status IN ('LOOKUP_PENDING', 'PENDING', 'QUEUED', 'RUNNING', 'RETRY_WAIT', 'REVIEWING', 'FAILED')"
            ),
        )
        batch_op.create_index(
            "OrganizeJob_workId_status_idx", ["workId", "status"], unique=False
        )

    op.create_table(
        "DuplicateCandidate",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("jobId", sa.String(length=191), nullable=False),
        sa.Column("targetWorkId", sa.String(length=191), nullable=False),
        sa.Column("reasons", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), server_default="0", nullable=False),
        sa.Column("suggestedAction", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jobId"], ["OrganizeJob.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["targetWorkId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("DuplicateCandidate", schema=None) as batch_op:
        batch_op.create_index(
            "DuplicateCandidate_jobId_status_idx", ["jobId", "status"], unique=False
        )
        batch_op.create_index(
            "DuplicateCandidate_suggestedAction_idx", ["suggestedAction"], unique=False
        )
        batch_op.create_index(
            "DuplicateCandidate_targetWorkId_idx", ["targetWorkId"], unique=False
        )

    op.create_table(
        "LibraryConsumptionState",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("userId", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("mediaKind", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=191), server_default="UNREAD", nullable=False
        ),
        sa.Column("lastEditionId", sa.String(length=191), nullable=True),
        sa.Column("lastVolumeId", sa.String(length=191), nullable=True),
        sa.Column("lastUnitId", sa.String(length=191), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lastEditionId"],
            ["LibraryEdition.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lastUnitId"],
            ["LibraryReadingUnit.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["lastVolumeId"],
            ["LibraryVolume.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["userId"], ["User.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("LibraryConsumptionState", schema=None) as batch_op:
        batch_op.create_index(
            "LibraryConsumptionState_user_work_media_key",
            ["userId", "workId", "mediaKind"],
            unique=True,
        )
        batch_op.create_index(
            "LibraryConsumptionState_workId_idx", ["workId"], unique=False
        )

    op.create_table(
        "MetadataLookupTask",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("workId", sa.String(length=191), nullable=False),
        sa.Column("editionId", sa.String(length=191), nullable=True),
        sa.Column("importTaskId", sa.String(length=191), nullable=True),
        sa.Column("organizeJobId", sa.String(length=191), nullable=True),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("providerOrder", sa.Text(), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("nextAttemptAt", TimestampMilliseconds(), nullable=True),
        sa.Column("resultSource", sa.Text(), nullable=True),
        sa.Column("candidateRawJson", sa.Text(), nullable=True),
        sa.Column("appliedFields", sa.Text(), nullable=True),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["editionId"],
            ["LibraryEdition.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["importTaskId"], ["ImportTask.id"], ondelete="SET NULL", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["organizeJobId"],
            ["OrganizeJob.id"],
            ondelete="SET NULL",
            onupdate="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workId"], ["LibraryWork.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("importTaskId", name="MetadataLookupTask_importTaskId_key"),
    )
    with op.batch_alter_table("MetadataLookupTask", schema=None) as batch_op:
        batch_op.create_index(
            "MetadataLookupTask_status_nextAttemptAt_idx",
            ["status", "nextAttemptAt"],
            unique=False,
        )
        batch_op.create_index(
            "MetadataLookupTask_workId_createdAt_idx",
            ["workId", "createdAt"],
            unique=False,
        )

    op.create_table(
        "MetadataSuggestion",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("jobId", sa.String(length=191), nullable=False),
        sa.Column("field", sa.String(length=191), nullable=False),
        sa.Column("currentValue", sa.Text(), nullable=True),
        sa.Column("suggestedValue", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=191), nullable=False),
        sa.Column("confidence", sa.Float(), server_default="0", nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jobId"], ["OrganizeJob.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("MetadataSuggestion", schema=None) as batch_op:
        batch_op.create_index("MetadataSuggestion_field_idx", ["field"], unique=False)
        batch_op.create_index(
            "MetadataSuggestion_jobId_status_idx", ["jobId", "status"], unique=False
        )
        batch_op.create_index("MetadataSuggestion_source_idx", ["source"], unique=False)

    op.create_table(
        "MetadataProviderExecution",
        sa.Column("id", sa.String(length=191), nullable=False),
        sa.Column("jobId", sa.String(length=191), nullable=True),
        sa.Column("lookupTaskId", sa.String(length=191), nullable=True),
        sa.Column("providerId", sa.String(length=191), nullable=False),
        sa.Column(
            "status", sa.String(length=32), server_default="PENDING", nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("rawResultJson", sa.Text(), nullable=True),
        sa.Column("errorSummary", sa.Text(), nullable=True),
        sa.Column("startedAt", TimestampMilliseconds(), nullable=True),
        sa.Column("finishedAt", TimestampMilliseconds(), nullable=True),
        sa.Column(
            "createdAt",
            TimestampMilliseconds(),
            server_default=sa.func.unixepoch() * 1000,
            nullable=False,
        ),
        sa.Column("updatedAt", TimestampMilliseconds(), nullable=False),
        sa.ForeignKeyConstraint(
            ["jobId"], ["OrganizeJob.id"], ondelete="CASCADE", onupdate="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lookupTaskId"],
            ["MetadataLookupTask.id"],
            ondelete="CASCADE",
            onupdate="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("MetadataProviderExecution", schema=None) as batch_op:
        batch_op.create_index(
            "MetadataProviderExecution_jobId_status_idx",
            ["jobId", "status"],
            unique=False,
        )
        batch_op.create_index(
            "MetadataProviderExecution_lookupTaskId_idx", ["lookupTaskId"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("MetadataProviderExecution", schema=None) as batch_op:
        batch_op.drop_index("MetadataProviderExecution_lookupTaskId_idx")
        batch_op.drop_index("MetadataProviderExecution_jobId_status_idx")

    op.drop_table("MetadataProviderExecution")
    with op.batch_alter_table("MetadataSuggestion", schema=None) as batch_op:
        batch_op.drop_index("MetadataSuggestion_source_idx")
        batch_op.drop_index("MetadataSuggestion_jobId_status_idx")
        batch_op.drop_index("MetadataSuggestion_field_idx")

    op.drop_table("MetadataSuggestion")
    with op.batch_alter_table("MetadataLookupTask", schema=None) as batch_op:
        batch_op.drop_index("MetadataLookupTask_workId_createdAt_idx")
        batch_op.drop_index("MetadataLookupTask_status_nextAttemptAt_idx")

    op.drop_table("MetadataLookupTask")
    with op.batch_alter_table("LibraryConsumptionState", schema=None) as batch_op:
        batch_op.drop_index("LibraryConsumptionState_workId_idx")
        batch_op.drop_index("LibraryConsumptionState_user_work_media_key")

    op.drop_table("LibraryConsumptionState")
    with op.batch_alter_table("DuplicateCandidate", schema=None) as batch_op:
        batch_op.drop_index("DuplicateCandidate_targetWorkId_idx")
        batch_op.drop_index("DuplicateCandidate_suggestedAction_idx")
        batch_op.drop_index("DuplicateCandidate_jobId_status_idx")

    op.drop_table("DuplicateCandidate")
    with op.batch_alter_table("OrganizeJob", schema=None) as batch_op:
        batch_op.drop_index("OrganizeJob_workId_status_idx")
        batch_op.drop_index(
            "OrganizeJob_unresolved_workId_key",
            sqlite_where=sa.text(
                "status IN ('LOOKUP_PENDING', 'PENDING', 'QUEUED', 'RUNNING', 'RETRY_WAIT', 'REVIEWING', 'FAILED')"
            ),
        )
        batch_op.drop_index("OrganizeJob_status_updatedAt_idx")
        batch_op.drop_index("OrganizeJob_runId_status_idx")
        batch_op.drop_index("OrganizeJob_importTaskId_idx")
        batch_op.drop_index("OrganizeJob_editionId_idx")

    op.drop_table("OrganizeJob")
    with op.batch_alter_table("LibraryReadingUnit", schema=None) as batch_op:
        batch_op.drop_index("LibraryReadingUnit_volumeId_unitType_sortOrder_key")
        batch_op.drop_index("LibraryReadingUnit_volumeId_sortOrder_idx")
        batch_op.drop_index("LibraryReadingUnit_fileId_sortOrder_idx")
        batch_op.drop_index("LibraryReadingUnit_editionId_unitType_idx")
        batch_op.drop_index("LibraryReadingUnit_editionId_sortOrder_idx")

    op.drop_table("LibraryReadingUnit")
    with op.batch_alter_table("KindleSendTask", schema=None) as batch_op:
        batch_op.drop_index("KindleSendTask_workId_createdAt_idx")
        batch_op.drop_index("KindleSendTask_userId_createdAt_idx")
        batch_op.drop_index("KindleSendTask_status_nextAttemptAt_createdAt_idx")
        batch_op.drop_index(
            "KindleSendTask_active_file_recipient_key",
            sqlite_where=sa.text("status IN ('queued', 'sending')"),
        )

    op.drop_table("KindleSendTask")
    with op.batch_alter_table("ImportLog", schema=None) as batch_op:
        batch_op.drop_index("ImportLog_importTaskId_createdAt_idx")

    op.drop_table("ImportLog")
    with op.batch_alter_table("ImportAsset", schema=None) as batch_op:
        batch_op.drop_index("ImportAsset_importTaskId_sortOrder_idx")

    op.drop_table("ImportAsset")
    with op.batch_alter_table("BookConversionTask", schema=None) as batch_op:
        batch_op.drop_index("BookConversionTask_status_createdAt_idx")
        batch_op.drop_index("BookConversionTask_sourceHash_idx")

    op.drop_table("BookConversionTask")
    with op.batch_alter_table("LibraryReadingProgress", schema=None) as batch_op:
        batch_op.drop_index("LibraryReadingProgress_workId_idx")
        batch_op.drop_index("LibraryReadingProgress_volumeId_idx")
        batch_op.drop_index("LibraryReadingProgress_userId_editionId_volumeId_key")
        batch_op.drop_index("LibraryReadingProgress_editionId_idx")
        batch_op.drop_index("LibraryReadingProgress_clientId_clientSequence_idx")

    op.drop_table("LibraryReadingProgress")
    with op.batch_alter_table("LibraryFile", schema=None) as batch_op:
        batch_op.drop_index("LibraryFile_volumeId_sortOrder_idx")
        batch_op.drop_index("LibraryFile_sizeBytes_mtimeMs_idx")
        batch_op.drop_index("LibraryFile_path_key")
        batch_op.drop_index("LibraryFile_fullHash_key")
        batch_op.drop_index("LibraryFile_fullHash_idx")
        batch_op.drop_index("LibraryFile_fingerprint_idx")
        batch_op.drop_index("LibraryFile_filePathHash_key")
        batch_op.drop_index("LibraryFile_editionId_sortOrder_idx")

    op.drop_table("LibraryFile")
    with op.batch_alter_table("ImportTask", schema=None) as batch_op:
        batch_op.drop_index("ImportTask_workId_idx")
        batch_op.drop_index("ImportTask_volumeId_idx")
        batch_op.drop_index("ImportTask_status_leaseExpiresAt_idx")
        batch_op.drop_index("ImportTask_status_createdAt_idx")
        batch_op.drop_index("ImportTask_monitorFolderId_status_idx")
        batch_op.drop_index("ImportTask_editionId_idx")
        batch_op.drop_index("ImportTask_createdAt_id_idx")
        batch_op.drop_index("ImportTask_contentHash_idx")

    op.drop_table("ImportTask")
    with op.batch_alter_table("ReaderBookmark", schema=None) as batch_op:
        batch_op.drop_index("ReaderBookmark_user_edition_idx")

    op.drop_table("ReaderBookmark")
    with op.batch_alter_table("LibraryVolume", schema=None) as batch_op:
        batch_op.drop_index("LibraryVolume_editionId_volumeIndex_idx")
        batch_op.drop_index("LibraryVolume_editionId_sortOrder_idx")

    op.drop_table("LibraryVolume")
    with op.batch_alter_table("LibraryMetadata", schema=None) as batch_op:
        batch_op.drop_index("LibraryMetadata_editionId_idx")

    op.drop_table("LibraryMetadata")
    with op.batch_alter_table("LibraryEditionFacet", schema=None) as batch_op:
        batch_op.drop_index("LibraryEditionFacet_editionId_idx")

    op.drop_table("LibraryEditionFacet")
    with op.batch_alter_table("WorkDetailPreference", schema=None) as batch_op:
        batch_op.drop_index("WorkDetailPreference_user_work_key")

    op.drop_table("WorkDetailPreference")
    with op.batch_alter_table("ShelfWork", schema=None) as batch_op:
        batch_op.drop_index("ShelfWork_workId_idx")
        batch_op.drop_index("ShelfWork_shelfId_createdAt_idx")

    op.drop_table("ShelfWork")
    with op.batch_alter_table("ReaderProgressCursor", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ReaderProgressCursor_workId"))
        batch_op.drop_index(batch_op.f("ix_ReaderProgressCursor_userId"))

    op.drop_table("ReaderProgressCursor")
    with op.batch_alter_table("ReaderBookPreference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ReaderBookPreference_workId"))
        batch_op.drop_index(batch_op.f("ix_ReaderBookPreference_userId"))

    op.drop_table("ReaderBookPreference")
    with op.batch_alter_table("LibraryWorkFacet", schema=None) as batch_op:
        batch_op.drop_index("LibraryWorkFacet_workId_idx")

    op.drop_table("LibraryWorkFacet")
    with op.batch_alter_table("LibraryEdition", schema=None) as batch_op:
        batch_op.drop_index("LibraryEdition_workId_versionKey_key")
        batch_op.drop_index("LibraryEdition_workId_primary_idx")
        batch_op.drop_index(
            "LibraryEdition_workId_mediaKind_primary_key",
            sqlite_where=sa.text("`primary` = 1 AND `hidden` = 0"),
        )
        batch_op.drop_index("LibraryEdition_workId_mediaKind_idx")
        batch_op.drop_index("LibraryEdition_sourceGroupKey_idx")
        batch_op.drop_index("LibraryEdition_monitorFolderId_idx")
        batch_op.drop_index("LibraryEdition_isbn_idx")
        batch_op.drop_index("LibraryEdition_identifier_idx")
        batch_op.drop_index("LibraryEdition_format_idx")

    op.drop_table("LibraryEdition")
    with op.batch_alter_table("UserMonitorFolderAccess", schema=None) as batch_op:
        batch_op.drop_index("UserMonitorFolderAccess_folder_idx")

    op.drop_table("UserMonitorFolderAccess")
    with op.batch_alter_table("LibraryWork", schema=None) as batch_op:
        batch_op.drop_index("LibraryWork_workType_idx")
        batch_op.drop_index("LibraryWork_trackingStatus_idx")
        batch_op.drop_index("LibraryWork_title_idx")
        batch_op.drop_index("LibraryWork_seriesName_idx")
        batch_op.drop_index("LibraryWork_publishedYear_idx")
        batch_op.drop_index("LibraryWork_publicationStatus_idx")
        batch_op.drop_index("LibraryWork_organized_idx")
        batch_op.drop_index("LibraryWork_organizeStatus_idx")
        batch_op.drop_index("LibraryWork_normalizedTitle_idx")
        batch_op.drop_index("LibraryWork_normalizedAuthor_idx")
        batch_op.drop_index("LibraryWork_monitorFolderId_idx")
        batch_op.drop_index("LibraryWork_mergeKey_idx")
        batch_op.drop_index("LibraryWork_hidden_idx")
        batch_op.drop_index("LibraryWork_createdAt_id_idx")

    op.drop_table("LibraryWork")
    op.drop_table("MonitorFolder")
    with op.batch_alter_table("UserPreference", schema=None) as batch_op:
        batch_op.drop_index("UserPreference_userId_idx")

    op.drop_table("UserPreference")
    with op.batch_alter_table("SourceSearchRecord", schema=None) as batch_op:
        batch_op.drop_index("SourceSearchRecord_title_idx")
        batch_op.drop_index("SourceSearchRecord_status_idx")
        batch_op.drop_index("SourceSearchRecord_sourceId_idx")
        batch_op.drop_index("SourceSearchRecord_providerType_idx")
        batch_op.drop_index("SourceSearchRecord_createdAt_idx")

    op.drop_table("SourceSearchRecord")
    with op.batch_alter_table("Shelf", schema=None) as batch_op:
        batch_op.drop_index("Shelf_updatedAt_idx")
        batch_op.drop_index("Shelf_ownerUserId_updatedAt_idx")
        batch_op.drop_index("Shelf_kind_updatedAt_idx")

    op.drop_table("Shelf")
    op.drop_table("Session")
    with op.batch_alter_table("ReaderPreference", schema=None) as batch_op:
        batch_op.drop_index("ReaderPreference_userId_idx")

    op.drop_table("ReaderPreference")
    with op.batch_alter_table("PasswordResetToken", schema=None) as batch_op:
        batch_op.drop_index("PasswordResetToken_userId_createdAt_idx")
        batch_op.drop_index("PasswordResetToken_expiresAt_idx")

    op.drop_table("PasswordResetToken")
    with op.batch_alter_table("LibraryOperation", schema=None) as batch_op:
        batch_op.drop_index("LibraryOperation_status_expiresAt_idx")
        batch_op.drop_index("LibraryOperation_action_createdAt_idx")

    op.drop_table("LibraryOperation")
    op.drop_table("User")
    op.drop_table("SystemSetting")
    op.drop_table("SystemHealthRun")
    with op.batch_alter_table("SystemEvent", schema=None) as batch_op:
        batch_op.drop_index("SystemEvent_targetType_targetId_idx")
        batch_op.drop_index("SystemEvent_source_createdAt_idx")
        batch_op.drop_index("SystemEvent_level_createdAt_idx")
        batch_op.drop_index("SystemEvent_createdAt_idx")
        batch_op.drop_index("SystemEvent_actorType_createdAt_idx")
        batch_op.drop_index("SystemEvent_action_createdAt_idx")

    op.drop_table("SystemEvent")
    with op.batch_alter_table("Source", schema=None) as batch_op:
        batch_op.drop_index("Source_providerType_idx")
        batch_op.drop_index("Source_priority_idx")
        batch_op.drop_index("Source_kind_idx")
        batch_op.drop_index("Source_enabled_idx")

    op.drop_table("Source")
    op.drop_table("QueueRuntimeState")
    with op.batch_alter_table("QueueControlOperation", schema=None) as batch_op:
        batch_op.drop_index("QueueControlOperation_queue_status_idx")

    op.drop_table("QueueControlOperation")
    with op.batch_alter_table("OrganizeRun", schema=None) as batch_op:
        batch_op.drop_index("OrganizeRun_status_createdAt_idx")

    op.drop_table("OrganizeRun")
    op.drop_table("OrganizePolicy")
    with op.batch_alter_table("MetadataProviderPipeline", schema=None) as batch_op:
        batch_op.drop_index("MetadataProviderPipeline_workType_position_idx")

    op.drop_table("MetadataProviderPipeline")
    with op.batch_alter_table("LibraryFacet", schema=None) as batch_op:
        batch_op.drop_index("LibraryFacet_kind_name_idx")

    op.drop_table("LibraryFacet")
    with op.batch_alter_table("ExternalMetadataCache", schema=None) as batch_op:
        batch_op.drop_index("ExternalMetadataCache_provider_queryKey_key")
        batch_op.drop_index("ExternalMetadataCache_provider_expiresAt_idx")

    op.drop_table("ExternalMetadataCache")
    with op.batch_alter_table("DownloadTask", schema=None) as batch_op:
        batch_op.drop_index("DownloadTask_type_idx")
        batch_op.drop_index("DownloadTask_status_createdAt_idx")
        batch_op.drop_index("DownloadTask_sourceId_idx")
        batch_op.drop_index("DownloadTask_searchRecordId_idx")
        batch_op.drop_index("DownloadTask_bookId_idx")

    op.drop_table("DownloadTask")
    with op.batch_alter_table("BookIdentityCache", schema=None) as batch_op:
        batch_op.drop_index("BookIdentityCache_parserVersion_idx")

    op.drop_table("BookIdentityCache")
    # ### end Alembic commands ###
